package: false
rememberMeChecked: false
hideLoginCheckbox: false
handleSessionTimeout: true
loginColorsInverted: true
requestTimeout: 10
initialConfig:
  baseUrl: https://cloud.sibvisions.com/previewer/services/mobile
  appName: Previewer
  appMode: full
startupParameter:
  test.parameter: false