name: flutter_jvx
description: A generic Flutter app for JVx applications.
homepage: https://www.sibvisions.com/
repository: https://github.com/sibvisions/flutter_jvx
issue_tracker: https://github.com/sibvisions/flutter_jvx/issues

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  # Flutter Dep
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # iOS Dep
  cupertino_icons: ^1.0.2

  # Translations capability
  intl: ^0.17.0

  material_color_generator: ^1.1.0

  # Config
  shared_preferences: ^2.0.15

  # Device Identification
  package_info_plus: ^1.4.2
  device_info_plus: ^4.1.0
  uuid: ^3.0.6

  # Util
  collection: ^1.16.0
  rxdart: ^0.27.5

  # IO handling
  universal_io: ^2.0.4
  universal_html: ^2.0.8

  # SVG Support
  flutter_svg: ^1.1.4
  flutter_svg_provider: ^1.0.3
  # Icons
  font_awesome_flutter: ^10.2.1
  # Managing different persistent classes
  get_it: ^7.2.0
  # QR Scanner
  mobile_scanner: ^2.0.0
  # Signature Pad
  signature: ^5.2.1
  # Saving files on system
  path: ^1.8.1
  path_provider: ^2.0.11
  # Zip files handling
  archive: ^3.3.1
  # Special Slivers for lists and grids
  sliver_tools: ^0.2.7
  # Auto resizing text widget
  auto_size_text: ^3.0.0
  # Used for routing with navigator 2.0
  beamer: ^1.5.2
  # Used for offline mode
  sqflite: ^2.0.3
  wakelock: ^0.6.2

  # Custom Dependencies
  flutter_picker: ^2.0.5
  flutter_map: ^2.2.0
  latlong2: ^0.8.1
  scrollable_positioned_list: ^0.3.1
  syncfusion_flutter_charts: ^20.1.55
  syncfusion_flutter_gauges: ^20.1.55
  url_launcher: ^6.1.5
  linked_scroll_controller: ^0.2.0
  liquid_progress_indicator: ^0.4.0

  #  charts_flutter: ^0.12.0
  charts_flutter:
    git:
      url: https://github.com/kennenfromchina/charts.git
      path: charts_flutter
      ref: fix_flutter3.0
  gauges: ^1.0.0
  image_picker: ^0.8.5+3
  file_picker: ^5.0.1
  file_saver: ^0.1.1

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/config/
    - assets/images/
