name: jvx_flutterclient
description: A generic Flutter app for JVx applications.
homepage: https://www.sibvisions.com
repository: https://github.com/sibvisions/flutterclient.git
issue_tracker: https://github.com/sibvisions/flutterclient/issues

# Format: version+buildNumber 
# Increase Build number every AppStore build (even for testing like TestFlight)  
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_widgets: ^0.1.12
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^0.1.2
  http: ^0.12.1
  font_awesome_flutter: ^8.5.0
  json_annotation: ^2.4.0
  shared_preferences: ^0.5.7+3
  shared_preferences_web: ^0.1.2+7
  flutter_picker: ^1.1.0
  path_provider: ^1.6.7
  archive: ^2.0.13
  xml: ^3.2.0 
  gson: ^0.1.2
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0
  equatable: ^0.2.0
  keyboard_actions: ^2.1.2
  file_picker: ^1.4.2
  image_picker: ^0.6.1+11
  package_info: ^0.4.0+13
  flutter_slidable: "^0.5.4"
  barcode_scan: ^3.0.1
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git
  connectivity: ^0.4.6+1
  uuid: ^2.0.4
  sticky_headers: ^0.1.8+1
  auto_size_text: ^2.1.0
  tinycolor: ^1.0.2
  flutter_swiper : ^1.1.6
  universal_io: ^1.0.1
  universal_html: ^1.2.3
  url_launcher: ^5.5.0
  responsive_builder: ^0.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - env/
    - assets/images/
    - locale/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
          style: normal
        - asset: assets/fonts/Quicksand_Bold.otf
          weight: 700

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          style: normal
        - asset: assets/fonts/Raleway-Medium.ttf