name: jvx_mobile_v3
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^0.1.2
  http_middleware: ^1.0.0
  http: ^0.11.3+16
  font_awesome_flutter:
  json_annotation: ^2.4.0
  shared_preferences: ^0.5.3+4
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git
  path_provider: any
  archive: ^2.0.10
  xml: ^3.2.0
  gson: ^0.1.2
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0
  equatable: ^0.2.0
  intl: ^0.15.8
  keyboard_actions: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/sib_visions.jpg
    - assets/images/sibvisions.png
    - locale/i18n_en.json
    - locale/i18n_de.json
    - env/conf.json

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
          style: normal
        - asset: assets/fonts/Quicksand_Bold.otf
          weight: 700

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          style: normal
        - asset: assets/fonts/Raleway-Medium.ttf