name: flutter_client
description: Generic Client
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  # Flutter Dep
  flutter_lints: ^1.0.0
  flutter:
    sdk: flutter

  # IOS Dep
  cupertino_icons: ^1.0.2

  # Custom  Dep
    # REST handling
  http: ^0.13.4
    # Icons
  font_awesome_flutter: ^9.2.0
    # Translations capability
  intl: ^0.17.0
    # Managing different persistent classes
  get_it: ^7.2.0
    # QR Scanner
  mobile_scanner: ^0.1.1
    # Saving files on system
  path_provider: ^2.0.9
    # handling zip files
  archive: ^3.2.2
    # Special Slivers for lists and grids
  sliver_tools: ^0.2.5
    # Auto resizing text widget
  auto_size_text: ^3.0.0

flutter:

  uses-material-design: true