name: flutter_client
description: Generic Client
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  # Flutter Dep
  flutter_lints: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # IOS Dep
  cupertino_icons: ^1.0.2

  # Custom  Dep
    # REST handling
  http: ^0.13.4
    # Icons
  font_awesome_flutter: ^9.2.0
    # Translations capability
  intl: ^0.17.0
    # Managing different persistent classes
  get_it: ^7.2.0
    # QR Scanner
  mobile_scanner: ^1.0.0
    # Saving files on system
  path_provider: ^2.0.9
    # handling zip files
  archive: ^3.2.2
    # Special Slivers for lists and grids
  sliver_tools: ^0.2.5
    # Auto resizing text widget
  auto_size_text: ^3.0.0
    # Used for routing with navigator 2.0
  beamer: ^1.4.0+1
    # Used for offline mode
  sqflite: ^2.0.3
  path: ^1.8.2
  flutter_map: ^0.14.0
  latlong2: ^0.8.1
  scrollable_positioned_list: ^0.3.1
  syncfusion_flutter_charts: ^20.1.55
  syncfusion_flutter_gauges: ^20.1.55
  url_launcher: ^6.1.2
  signature: ^5.0.1
  flutter_picker: ^2.0.3
  linked_scroll_controller: ^0.2.0
  charts_flutter: ^0.12.0
  gauges: ^1.0.0

flutter:
  assets:
    - assets/config/app.conf.json
    - assets/images/

  uses-material-design: true