name: Test app

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v1.3.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      - name: Install app dependencies
        run: flutter pub get
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      - name: Test app
        run: flutter test test/
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
