name: Update Version CI

on:
  push:
    branches: [master]
  pull_request: [master]

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@master
        with:
          persistent-credentials: false
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run-script updateVersion
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Update Version Action"
          git commit -m "Updated version" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
